export type ActivitySuggestion = {
  value: string
  label: string
}

// Curated suggestions to keep the UX predictable.
// We can later expand this list using Google returned `types`/`primaryType`.
export const ACTIVITY_SUGGESTIONS: ActivitySuggestion[] = [
  // Nightlife & Entertainment
  { value: 'clubbing', label: 'Clubbing' },
  { value: 'dancing', label: 'Dancing' },
  { value: 'nightclub', label: 'Nightclub' },
  { value: 'bar', label: 'Bar / Nightlife' },
  { value: 'live music', label: 'Live Music' },
  { value: 'karaoke', label: 'Karaoke' },
  { value: 'comedy club', label: 'Comedy Club' },
  { value: 'stand-up comedy', label: 'Stand-up Comedy' },
  { value: 'sports bar', label: 'Sports Bar' },
  { value: 'pub', label: 'Pub' },
  { value: 'lounge', label: 'Lounge' },
  { value: 'speakeasy', label: 'Speakeasy' },
  { value: 'jazz club', label: 'Jazz Club' },
  { value: 'rooftop bar', label: 'Rooftop Bar' },
  { value: 'wine bar', label: 'Wine Bar' },
  { value: 'cocktail bar', label: 'Cocktail Bar' },
  { value: 'piano bar', label: 'Piano Bar' },

  // Food & Dining Experiences
  { value: 'restaurant', label: 'Restaurant' },
  { value: 'fine dining', label: 'Fine Dining' },
  { value: 'food tour', label: 'Food Tour' },
  { value: 'cooking class', label: 'Cooking Class' },
  { value: 'wine tasting', label: 'Wine Tasting' },
  { value: 'brewery tour', label: 'Brewery Tour' },
  { value: 'distillery tour', label: 'Distillery Tour' },
  { value: 'food truck', label: 'Food Truck' },
  { value: 'farmers market', label: 'Farmers Market' },
  { value: 'dessert shop', label: 'Dessert Shop' },
  { value: 'ice cream parlor', label: 'Ice Cream Parlor' },
  { value: 'chocolate tasting', label: 'Chocolate Tasting' },
  { value: 'cheese tasting', label: 'Cheese Tasting' },
  { value: 'coffee tasting', label: 'Coffee Tasting / Cupping' },
  { value: 'high tea', label: 'High Tea / Afternoon Tea' },

  // Arts & Culture
  { value: 'art gallery', label: 'Art Gallery' },
  { value: 'museum', label: 'Museum' },
  { value: 'history museum', label: 'History Museum' },
  { value: 'science museum', label: 'Science Museum' },
  { value: 'contemporary art', label: 'Contemporary Art' },
  { value: 'theater', label: 'Theater' },
  { value: 'broadway show', label: 'Broadway Show / Musical' },
  { value: 'opera', label: 'Opera' },
  { value: 'ballet', label: 'Ballet / Dance Performance' },
  { value: 'symphony', label: 'Symphony / Orchestra' },
  { value: 'cinema', label: 'Cinema / Movie Theater' },
  { value: 'drive-in movie', label: 'Drive-In Movie' },
  { value: 'film festival', label: 'Film Festival' },
  { value: 'improv show', label: 'Improv Show' },
  { value: 'planetarium', label: 'Planetarium' },
  { value: 'observatory', label: 'Observatory' },
  { value: 'cultural festival', label: 'Cultural Festival' },
  { value: 'heritage site', label: 'Heritage Site' },
  { value: 'monument', label: 'Monument / Landmark' },
  { value: 'historical tour', label: 'Historical Tour' },
  { value: 'architecture tour', label: 'Architecture Tour' },
  { value: 'ghost tour', label: 'Ghost Tour' },

  // Outdoor & Nature
  { value: 'hiking', label: 'Hiking' },
  { value: 'nature walk', label: 'Nature Walk' },
  { value: 'park', label: 'Park / Picnic' },
  { value: 'botanical garden', label: 'Botanical Garden' },
  { value: 'arboretum', label: 'Arboretum' },
  { value: 'beach', label: 'Beach' },
  { value: 'lake', label: 'Lake Activities' },
  { value: 'river walk', label: 'River Walk' },
  { value: 'waterfront', label: 'Waterfront / Pier' },
  { value: 'zoo', label: 'Zoo' },
  { value: 'aquarium', label: 'Aquarium' },
  { value: 'wildlife safari', label: 'Wildlife Safari' },
  { value: 'bird watching', label: 'Bird Watching' },
  { value: 'stargazing', label: 'Stargazing' },
  { value: 'sunset viewing', label: 'Sunset Viewing' },
  { value: 'camping', label: 'Camping' },
  { value: 'glamping', label: 'Glamping' },
  { value: 'fishing', label: 'Fishing' },
  { value: 'kayaking', label: 'Kayaking' },
  { value: 'canoeing', label: 'Canoeing' },
  { value: 'paddleboarding', label: 'Paddleboarding' },
  { value: 'sailing', label: 'Sailing' },
  { value: 'boat tour', label: 'Boat Tour' },
  { value: 'cruise', label: 'Cruise' },

  // Sports & Recreation
  { value: 'bowling', label: 'Bowling' },
  { value: 'mini golf', label: 'Mini Golf' },
  { value: 'golf', label: 'Golf' },
  { value: 'driving range', label: 'Driving Range' },
  { value: 'tennis', label: 'Tennis' },
  { value: 'pickleball', label: 'Pickleball' },
  { value: 'badminton', label: 'Badminton' },
  { value: 'squash', label: 'Squash / Racquetball' },
  { value: 'basketball', label: 'Basketball' },
  { value: 'volleyball', label: 'Volleyball' },
  { value: 'soccer', label: 'Soccer / Football' },
  { value: 'rock climbing', label: 'Rock Climbing / Bouldering' },
  { value: 'indoor climbing', label: 'Indoor Climbing' },
  { value: 'hiking trail', label: 'Hiking Trail' },
  { value: 'cycling', label: 'Cycling / Biking' },
  { value: 'mountain biking', label: 'Mountain Biking' },
  { value: 'skating', label: 'Ice Skating' },
  { value: 'roller skating', label: 'Roller Skating' },
  { value: 'skateboarding', label: 'Skateboarding' },
  { value: 'yoga', label: 'Yoga Class' },
  { value: 'pilates', label: 'Pilates' },
  { value: 'dance class', label: 'Dance Class' },
  { value: 'fitness class', label: 'Fitness Class' },
  { value: 'martial arts', label: 'Martial Arts' },
  { value: 'fencing', label: 'Fencing' },
  { value: 'archery', label: 'Archery' },
  { value: 'shooting range', label: 'Shooting Range' },
  { value: 'horseback riding', label: 'Horseback Riding' },
  { value: 'skiing', label: 'Skiing / Snowboarding' },
  { value: 'snowshoeing', label: 'Snowshoeing' },
  { value: 'swimming', label: 'Swimming' },
  { value: 'surfing', label: 'Surfing' },
  { value: 'scuba diving', label: 'Scuba Diving' },
  { value: 'snorkeling', label: 'Snorkeling' },

  // Games & Fun
  { value: 'arcade', label: 'Arcade' },
  { value: 'board game cafe', label: 'Board Game Cafe' },
  { value: 'escape room', label: 'Escape Room' },
  { value: 'axe throwing', label: 'Axe Throwing' },
  { value: 'paintball', label: 'Paintball' },
  { value: 'laser tag', label: 'Laser Tag' },
  { value: 'go-karting', label: 'Go-Karting' },
  { value: 'trampoline park', label: 'Trampoline Park' },
  { value: 'indoor playground', label: 'Indoor Adventure Park' },
  { value: 'virtual reality', label: 'Virtual Reality Experience' },
  { value: 'billiards', label: 'Billiards / Pool' },
  { value: 'ping pong', label: 'Ping Pong' },
  { value: 'shuffleboard', label: 'Shuffleboard' },
  { value: 'darts', label: 'Darts' },
  { value: 'cornhole', label: 'Cornhole' },
  { value: 'casino', label: 'Casino / Gambling' },
  { value: 'bingo', label: 'Bingo' },
  { value: 'trivia night', label: 'Trivia Night' },
  { value: 'puzzle room', label: 'Puzzle Room' },
  { value: 'treasure hunt', label: 'Treasure Hunt / Scavenger Hunt' },

  // Relaxation & Wellness
  { value: 'spa', label: 'Spa' },
  { value: 'massage', label: 'Massage' },
  { value: 'hot springs', label: 'Hot Springs' },
  { value: 'sauna', label: 'Sauna / Steam Room' },
  { value: 'meditation', label: 'Meditation Class' },
  { value: 'yoga retreat', label: 'Yoga Retreat' },
  { value: 'wellness retreat', label: 'Wellness Retreat' },
  { value: 'salt cave', label: 'Salt Cave Therapy' },
  { value: 'float therapy', label: 'Float Therapy / Sensory Deprivation' },
  { value: 'meditation garden', label: 'Meditation Garden' },
  { value: 'tea ceremony', label: 'Tea Ceremony' },

  // Shopping & Browsing
  { value: 'shopping mall', label: 'Shopping Mall' },
  { value: 'boutique shopping', label: 'Boutique Shopping' },
  { value: 'thrift shopping', label: 'Thrift Shopping / Vintage' },
  { value: 'flea market', label: 'Flea Market' },
  { value: 'antique shopping', label: 'Antique Shopping' },
  { value: 'bookstore', label: 'Bookstore / Library' },
  { value: 'record store', label: 'Record Store' },
  { value: 'art supply store', label: 'Art Supply Store' },
  { value: 'specialty food market', label: 'Specialty Food Market' },
  { value: 'window shopping', label: 'Window Shopping' },

  // Creative & Hands-On
  { value: 'art class', label: 'Art Class / Workshop' },
  { value: 'pottery class', label: 'Pottery / Ceramics Class' },
  { value: 'painting class', label: 'Painting Class' },
  { value: 'drawing class', label: 'Drawing / Sketching Class' },
  { value: 'photography tour', label: 'Photography Tour / Workshop' },
  { value: 'jewelry making', label: 'Jewelry Making Workshop' },
  { value: 'candle making', label: 'Candle Making' },
  { value: 'soap making', label: 'Soap Making' },
  { value: 'flower arranging', label: 'Flower Arranging' },
  { value: 'glassblowing', label: 'Glassblowing Workshop' },
  { value: 'woodworking', label: 'Woodworking Class' },
  { value: 'knitting', label: 'Knitting / Crochet Circle' },
  { value: 'sewing class', label: 'Sewing / Fashion Design' },
  { value: 'diy workshop', label: 'DIY Workshop' },
  { value: 'mixology class', label: 'Mixology / Bartending Class' },

  // Music & Performance
  { value: 'concert', label: 'Concert / Live Show' },
  { value: 'open mic', label: 'Open Mic Night' },
  { value: 'poetry reading', label: 'Poetry Reading / Slam' },
  { value: 'storytelling', label: 'Storytelling Event' },
  { value: 'burlesque', label: 'Burlesque Show' },
  { value: 'drag show', label: 'Drag Show' },
  { value: 'cabaret', label: 'Cabaret' },
  { value: 'dance performance', label: 'Dance Performance' },
  { value: 'musical theater', label: 'Musical Theater' },
  { value: 'battle of the bands', label: 'Battle of the Bands' },
  { value: 'dj set', label: 'DJ Set / Electronic Music' },
  { value: 'classical concert', label: 'Classical Music Concert' },
  { value: 'chamber music', label: 'Chamber Music' },
  { value: 'choir performance', label: 'Choir / Vocal Performance' },
  { value: 'acoustic set', label: 'Acoustic Set / Unplugged' },
  { value: 'kirtan', label: 'Kirtan / Chanting' },

  // Social & Community
  { value: 'networking event', label: 'Networking Event' },
  { value: 'meetup', label: 'Meetup / Social Gathering' },
  { value: 'language exchange', label: 'Language Exchange' },
  { value: 'book club', label: 'Book Club' },
  { value: 'wine club', label: 'Wine Club' },
  { value: 'volunteer activity', label: 'Volunteer Activity' },
  { value: 'community garden', label: 'Community Garden' },
  { value: 'charity event', label: 'Charity Event / Fundraiser' },
  { value: 'speed dating', label: 'Speed Dating' },
  { value: 'mixer', label: 'Social Mixer' },

  // Learning & Educational
  { value: 'lecture', label: 'Lecture / Talk' },
  { value: 'workshop', label: 'Educational Workshop' },
  { value: 'seminar', label: 'Seminar / Conference' },
  { value: 'tour', label: 'Guided Tour' },
  { value: 'wine education', label: 'Wine Education Class' },
  { value: 'beer education', label: 'Beer Education / Cicerone' },
  { value: 'spirit tasting', label: 'Whiskey / Spirit Tasting' },
  { value: 'cheese making', label: 'Cheese Making Class' },
  { value: 'chocolate making', label: 'Chocolate Making' },
  { value: 'bread baking', label: 'Bread Baking Class' },
  { value: 'pasta making', label: 'Pasta Making Class' },
  { value: 'sushi class', label: 'Sushi Making Class' },
  { value: 'language class', label: 'Language Class' },
  { value: 'coding workshop', label: 'Coding / Tech Workshop' },
  { value: 'financial seminar', label: 'Financial Seminar' },
  { value: 'writing workshop', label: 'Writing / Creative Writing' },
  { value: 'public speaking', label: 'Public Speaking / Toastmasters' },

  // Seasonal & Special Events
  { value: 'holiday event', label: 'Holiday Event / Celebration' },
  { value: 'fireworks', label: 'Fireworks Display' },
  { value: 'parade', label: 'Parade' },
  { value: 'street fair', label: 'Street Fair / Festival' },
  { value: 'carnival', label: 'Carnival / Fun Fair' },
  { value: 'circus', label: 'Circus Performance' },
  { value: 'amusement park', label: 'Amusement Park / Theme Park' },
  { value: 'water park', label: 'Water Park' },
  { value: 'county fair', label: 'County / State Fair' },
  { value: 'renaissance fair', label: 'Renaissance Fair' },
  { value: 'christmas market', label: 'Christmas Market' },
  { value: 'pumpkin patch', label: 'Pumpkin Patch' },
  { value: 'apple picking', label: 'Apple Picking' },
  { value: 'berry picking', label: 'Berry / Fruit Picking' },
  { value: 'haunted house', label: 'Haunted House / Halloween Event' },
  { value: 'corn maze', label: 'Corn Maze' },
  { value: 'hayride', label: 'Hayride' },
  { value: 'bonfire', label: 'Bonfire / Beach Fire' },

  // Unique & Unusual
  { value: 'cat cafe', label: 'Cat Cafe' },
  { value: 'dog cafe', label: 'Dog Cafe / Puppy Cafe' },
  { value: 'owl cafe', label: 'Owl / Bird Cafe' },
  { value: 'hedgehog cafe', label: 'Hedgehog / Small Animal Cafe' },
  { value: 'reptile center', label: 'Reptile Center / Zoo' },
  { value: 'insectarium', label: 'Insectarium / Butterfly House' },
  { value: 'mystery dinner', label: 'Mystery Dinner Theater' },
  { value: 'dinner train', label: 'Dinner Train / Scenic Rail' },
  { value: 'dinner cruise', label: 'Dinner Cruise' },
  { value: 'underground tour', label: 'Underground / Cave Tour' },
  { value: 'submarine tour', label: 'Submarine Tour' },
  { value: 'helicopter tour', label: 'Helicopter Tour' },
  { value: 'hot air balloon', label: 'Hot Air Balloon Ride' },
  { value: 'skydiving', label: 'Skydiving' },
  { value: 'bungee jumping', label: 'Bungee Jumping' },
  { value: 'zip lining', label: 'Zip Lining' },
  { value: 'paragliding', label: 'Paragliding' },
  { value: 'paramotoring', label: 'Paramotoring' },
  { value: 'ferris wheel', label: 'Ferris Wheel / Observation Wheel' },
  { value: 'observation deck', label: 'Observation Deck / Viewing Platform' },
  { value: 'rooftop pool', label: 'Rooftop Pool' },
  { value: 'igloo dining', label: 'Igloo / Dome Dining' },
  { value: 'dining in the dark', label: 'Dining in the Dark' },
  { value: 'silent disco', label: 'Silent Disco' },
  { value: 'murder mystery', label: 'Murder Mystery Party' },
  { value: 'immersion theater', label: 'Immersive Theater Experience' },
  { value: 'sleepover at museum', label: 'Sleepover at Museum / Zoo' },
  { value: 'midnight movie', label: 'Midnight Movie Screening' },
  { value: 'planetarium show', label: 'Planetarium Laser Show' },
  { value: 'IMAX theater', label: 'IMAX / Dome Theater' },
  { value: '4D cinema', label: '4D / Motion Cinema' },
  { value: 'virtual tour', label: 'Virtual / Digital Art Experience' },
  { value: 'projection mapping', label: 'Projection Mapping Show' },
  { value: 'drone show', label: 'Drone Light Show' },
  { value: 'laser show', label: 'Laser Light Show' },

  // Adult-Only / Night Activities
  { value: 'casino night', label: 'Casino Night' },
  { value: 'poker tournament', label: 'Poker Tournament' },
  { value: 'burlesque class', label: 'Burlesque / Pole Dancing Class' },
  { value: 'salsa class', label: 'Salsa / Latin Dance Class' },
  { value: 'tango class', label: 'Tango Class' },
  { value: 'ballroom dancing', label: 'Ballroom Dancing' },
  { value: 'swing dancing', label: 'Swing / Lindy Hop Dancing' },
  { value: 'blues dancing', label: 'Blues Dancing' },
  { value: 'bachata class', label: 'Bachata / Kizomba Class' },
  { value: 'belly dancing', label: 'Belly Dancing Class' },
  { value: 'flamenco', label: 'Flamenco Show / Class' },
  { value: 'irish dancing', label: 'Irish Step Dancing' },
  { value: 'tap dancing', label: 'Tap Dancing' },
  { value: 'hip hop class', label: 'Hip Hop Dance Class' },
  { value: 'contemporary dance', label: 'Contemporary Dance' },
  { value: 'ballet class', label: 'Ballet Class' },
  { value: 'aerial silks', label: 'Aerial Silks / Circus Arts' },
  { value: 'trapeze', label: 'Flying Trapeze Class' },
  { value: 'pole fitness', label: 'Pole Fitness / Aerial Hoop' },

  // Tech & Gaming
  { value: 'esports', label: 'Esports Tournament / Gaming' },
  { value: 'gaming lounge', label: 'Gaming Lounge / PC Cafe' },
  { value: 'console gaming', label: 'Console Gaming Party' },
  { value: 'VR gaming', label: 'Virtual Reality Gaming' },
  { value: 'AR experience', label: 'Augmented Reality Experience' },
  { value: 'escape room VR', label: 'VR Escape Room' },
  { value: 'motion simulator', label: 'Motion Simulator Ride' },
  { value: 'flight simulator', label: 'Flight Simulator' },
  { value: 'racing simulator', label: 'Racing / F1 Simulator' },
  { value: 'robotics workshop', label: 'Robotics / Maker Workshop' },
  { value: '3D printing', label: '3D Printing Workshop' },
  { value: 'drone flying', label: 'Drone Flying Lesson' },
  { value: 'tech meetup', label: 'Tech Meetup / Hackathon' },
]
